# Generated by Django 4.1.7 on 2023-03-23 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, default='settings.MEDIA_ROOT/img/no_image.png', null=True, upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='house_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house_details',
            name='multipleimages',
            field=models.ForeignKey(default='settings.MEDIA_ROOT/img/no_image.png', on_delete=django.db.models.deletion.CASCADE, related_name='multiple_images', to='Houses.multipleimage'),
        ),
    ]
