# Generated by Django 4.1.7 on 2023-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_location',
            options={'ordering': ['location'], 'verbose_name': 'House Location', 'verbose_name_plural': 'House Locations'},
        ),
        migrations.AlterField(
            model_name='house_location',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='house_location',
            index=models.Index(fields=['location'], name='Houses_hous_locatio_c7add4_idx'),
        ),
    ]
