# Generated by Django 4.1.7 on 2023-03-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0002_alter_house_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_details',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='house_location',
            options={'ordering': ['locationName'], 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['id', 'slug'], name='Houses_hous_id_14c024_idx'),
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['title'], name='Houses_hous_title_3201f1_idx'),
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['-posted'], name='Houses_hous_posted_d94360_idx'),
        ),
    ]
