# Generated by Django 4.1.7 on 2023-03-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0003_alter_house_details_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='house_details',
            new_name='House_Detai_id_a1fb19_idx',
            old_name='Houses_hous_id_14c024_idx',
        ),
        migrations.RenameIndex(
            model_name='house_details',
            new_name='House_Detai_title_2a0bde_idx',
            old_name='Houses_hous_title_3201f1_idx',
        ),
        migrations.RenameIndex(
            model_name='house_details',
            new_name='House_Detai_posted_602927_idx',
            old_name='Houses_hous_posted_d94360_idx',
        ),
        migrations.RenameIndex(
            model_name='house_location',
            new_name='House_Locat_locatio_0b4627_idx',
            old_name='Houses_hous_locatio_c727ec_idx',
        ),
        migrations.AlterModelTable(
            name='house_details',
            table='House_Details',
        ),
        migrations.AlterModelTable(
            name='house_location',
            table='House_Location',
        ),
    ]
