# Generated by Django 4.1.7 on 2023-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0003_house_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='house_details',
            name='owners_contact',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
