# Generated by Django 4.1.7 on 2023-03-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0003_alter_house_details_multipleimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='multipleimages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_images', to='Houses.multipleimage'),
        ),
    ]
