# Generated by Django 4.1.7 on 2023-11-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0003_alter_house_details_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
