# Generated by Django 4.1.7 on 2023-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0004_alter_house_details_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='thumbnail',
            field=models.ImageField(default='media/no_image.png', upload_to='img'),
        ),
    ]
