# Generated by Django 4.1.7 on 2023-03-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0001_initial'),
        ('Houses', '0004_rename_houses_hous_id_14c024_idx_house_detai_id_a1fb19_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.house_location'),
        ),
        migrations.DeleteModel(
            name='House_Location',
        ),
    ]
