# Generated by Django 4.1.7 on 2023-03-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0005_alter_house_details_location_delete_house_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='House_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['locationName'],
            },
        ),
        migrations.AlterModelOptions(
            name='house_details',
            options={'ordering': ['-posted']},
        ),
        migrations.RemoveIndex(
            model_name='house_details',
            name='House_Detai_id_a1fb19_idx',
        ),
        migrations.RemoveIndex(
            model_name='house_details',
            name='House_Detai_title_2a0bde_idx',
        ),
        migrations.RemoveIndex(
            model_name='house_details',
            name='House_Detai_posted_602927_idx',
        ),
        migrations.AlterModelTable(
            name='house_details',
            table=None,
        ),
        migrations.AddIndex(
            model_name='house_location',
            index=models.Index(fields=['locationName'], name='Houses_hous_locatio_c727ec_idx'),
        ),
        migrations.AlterField(
            model_name='house_details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.house_location'),
        ),
    ]
