# Generated by Django 4.1.7 on 2023-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_amount',
            field=models.IntegerField(default=300),
        ),
    ]
