# Generated by Django 4.1.7 on 2023-03-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('1 br', 'One bedroom'), ('2 br', 'Two bedroom'), ('3 br', 'Three bedroom')], max_length=4)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='House_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.AddIndex(
            model_name='house_location',
            index=models.Index(fields=['location_name'], name='Agency_hous_locatio_668a63_idx'),
        ),
        migrations.AddField(
            model_name='house_details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Agency.house_location'),
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['id', 'slug'], name='Agency_hous_id_367c66_idx'),
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['category_name'], name='Agency_hous_categor_e518b2_idx'),
        ),
        migrations.AddIndex(
            model_name='house_details',
            index=models.Index(fields=['-posted'], name='Agency_hous_posted_042968_idx'),
        ),
    ]
