# Generated by Django 4.1.7 on 2023-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'AgencyHouse_Location',
                'ordering': ['locationName'],
            },
        ),
        migrations.AddIndex(
            model_name='house_location',
            index=models.Index(fields=['locationName'], name='AgencyHouse_locatio_bf1a10_idx'),
        ),
    ]
