# Generated by Django 4.1.7 on 2023-03-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_details',
            old_name='price',
            new_name='rent_amount',
        ),
    ]
