# Generated by Django 4.1.7 on 2023-03-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0006_house_location_alter_house_details_options_and_more'),
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House_Location',
        ),
    ]
