# Generated by Django 4.1.7 on 2023-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0003_alter_house_details_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='available',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=2),
        ),
    ]
