# Generated by Django 4.1.7 on 2023-03-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0004_alter_house_details_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
