# Generated by Django 4.1.7 on 2023-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0005_alter_house_details_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='category_name',
            field=models.CharField(choices=[('beds', 'Bedsitter'), ('1 br', 'One bedroom'), ('2 br', 'Two bedroom'), ('3 br', 'Three bedroom'), ('4 br', 'Four bedroom')], max_length=4),
        ),
    ]
