# Generated by Django 4.1.7 on 2023-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0006_alter_house_details_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='category_name',
            field=models.CharField(choices=[('beds', 'Bedsitter'), ('1br', 'One bedroom'), ('2br', 'Two bedroom'), ('3br', 'Three bedroom'), ('4br', 'Four bedroom')], max_length=4),
        ),
    ]
