# Generated by Django 4.1.7 on 2023-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0008_alter_house_details_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
    ]
