# Generated by Django 4.1.7 on 2023-03-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0010_multipleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
        migrations.RemoveField(
            model_name='house_details',
            name='image',
        ),
        migrations.AddField(
            model_name='house_details',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='image',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.house_details'),
        ),
    ]
