# Generated by Django 4.1.7 on 2023-03-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0012_alter_house_details_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='detail',
        ),
        migrations.AddField(
            model_name='house_details',
            name='images',
            field=models.ForeignKey(default='img/no_image.png', on_delete=django.db.models.deletion.CASCADE, related_name='house', to='Agency.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(default='img/no_image.png', upload_to='img'),
        ),
    ]
