# Generated by Django 4.1.7 on 2023-03-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0013_remove_image_detail_house_details_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_details',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='img'),
        ),
    ]
