# Generated by Django 4.1.7 on 2023-03-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0014_alter_house_details_images_alter_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_details',
            name='images',
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
