# Generated by Django 4.1.7 on 2023-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0015_remove_house_details_images_alter_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_details',
            name='images',
            field=models.ManyToManyField(related_name='house_view', to='Agency.image'),
        ),
    ]
